### ISSUE TITLE
Make the ratings read-only

### ISSUE THREAD

**Issue by neelra8n** [arifszn/reforge#93]
On Dashboard Screen ->
In the review section, stars should persist the clicked number of stars.
Existing -> 
 - rating is 1 (1 yellow star)
 - click 5th star 
 - reverts back to 1 starts

Expected -> 
 - rating is 1 (1 yellow star)
 - click 5th star 
 - retain 5 yellow stars

**Comment by neelra8n** [comment]
assign it to me...

**Comment by neelra8n** [comment]
yaa, after going through the code,I found so.

Rather than making it disabled. I'll remove the number of stars being shown.. 
That will enable viewers to play along

**Comment by arifszn** [comment]
Disabled will be better imo.

**Comment by arifszn** [comment]
Close via #105.
